name: Build and Deploy

on:
  push:
    tags:
      # # Regex for a version number such as YYYY-MM-DD.XXX
      - "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9].[0-9]+"

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build JS Deps
        run: |
          echo ${{github.ref_name}}
          ls Temml/dist
          cd mathml2omml
          npm install
          npm run transpile
          ls dist
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release
      - name: Rename
        run: |
          mv target/release/textocx.exe ./textocx-${{github.ref_name}}.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./textocx-${{github.ref_name}}.exe
